### PR TITLE
Create a logger for the module and use it for logging

### LINKED ISSUE #67: Use named logger
First and foremost I must say thanks for making this library! 😻  

**Is your feature request related to a problem? Please describe.**

If I enable debug logging for a worker/client all the loggers from the library are shown to belong to the root logger:

```
2020-10-22 18:04:04,968 | DEBUG    | root         | Grpc channel connectivity changed to: ChannelConnectivity.IDLE
2020-10-22 18:04:04,968 | DEBUG    | root         | Handling task {'type': 'fileops.files_exist', 'timeout': 10000, 'max_jobs_to_activate': 32, 'variables_to_fetch': ['file_list']}
2020-10-22 18:04:04,969 | DEBUG    | root         | Connected to localhost:26500
2020-10-22 18:04:04,969 | INFO     | root         | Retrying connection to localhost:26500
2020-10-22 18:04:04,969 | DEBUG    | root         | Grpc channel connectivity changed to: ChannelConnectivity.READY
2020-10-22 18:04:04,969 | DEBUG    | root         | Activating jobs for task: {'type': 'fileops.files_exist', 'timeout': 10000, 'max_jobs_to_activate': 32, 'variables_to_fetch': ['file_list']}
2020-10-22 18:04:04,969 | DEBUG    | root         | Connected to localhost:26500
```

Logging config used to get above output:

```py
logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s | %(levelname)-8s | %(name)-12s | %(message)s"
)
```

**Describe the solution you'd like**

In order to silence certain parts of the library, e.g. only show warnings for `pyzeebe.grpc_internals` (and its root loggers), the library can use named loggers.

The user can then use

```py
logging.getLogger("pyzeebe.grpc_internals").setLevel(logging.WARNING)
```

and the debug messages will be silenced from that particular logger (and children). 

Another advantage is that it will be clearer which logger is emitting the messages:

```
2020-10-22 19:15:42,346 | DEBUG    | pyzeebe.grpc_internals.zeebe_adapter_base | Grpc channel connectivity changed to: ChannelConnectivity.IDLE
2020-10-22 19:15:42,347 | DEBUG    | pyzeebe.worker.worker | Handling task {'type': 'fileops.files_exist', 'timeout': 10000, 'max_jobs_to_activate': 32, 'variables_to_fetch': ['file_list']}
2020-10-22 19:15:42,347 | DEBUG    | pyzeebe.grpc_internals.zeebe_adapter_base | Connected to localhost:26500
2020-10-22 19:15:42,348 | INFO     | pyzeebe.worker.worker | Retrying connection to localhost:26500
2020-10-22 19:15:42,348 | DEBUG    | pyzeebe.grpc_internals.zeebe_adapter_base | Grpc channel connectivity changed to: ChannelConnectivity.READY
```

**Describe alternatives you've considered**
n/a

**Additional context**
Popular StackOverflow post where I got the silencing functionality from: [How do I disable log messages from the Requests library?](https://stackoverflow.com/a/11029841/2670584)

### PR DESCRIPTION
**Pull request by kbakk**
Instantiate a logger using `logging.getLogger` and use this (e.g. `logger.debug(...)`) instead of the root logger (`logging.debug(...)`). 

See #67 for benefits / reason. 

## Changes

- Creates a logger in every module where `logging.(warning|info|debug)` was used and replace those occurences
- Updated one test to accommodate this change, and added another test to ensure that we log using module names

### New Features *(required)*

Loggers are now using module names instead of the root logger.

### Deprecations *(required)*

None. 

### Enhancements *(optional)*

n/a

## Checklist

- [x] Unit tests
- [ ] Documentation

## References

Fixes #67

### CODE REVIEW

**Comment by kbakk** [comment]
I am not sure this is something to worry about, but if you previously depended on the logger to be `root`, or what you named the root logger to, it will break with this.

**Comment by JonatanMartens** [comment]
First of all: thank you so much for your contribution, it really is appreciated greatly.

This is definitely something that I wanted to look into, but I don't have a lot of familiarity with the `logging` library.

One question:

If I wanted to disable the logger of the entire `pyzeebe` library could I accomplish this with:
```python
logging.getLogger("pyzeebe").setLevel(logging.WARNING)
```
or would I have to disable each internal module (`grpc_internals` for example)?

**Comment by kbakk** [comment]
> If I wanted to disable the logger of the entire `pyzeebe` library could I accomplish this with

Yes, that (your example) works. 

According to the [logging docs](https://docs.python.org/3/library/logging.html#logger-objects):

> For example, given a logger with a name of `foo`, loggers with names of `foo.bar`, `foo.bar.baz`, and `foo.bam` are all descendants of `foo`.
>
> ...
>
> **setLevel(level)**
>
> The term ‘delegation to the parent’ means that if a logger has a level of NOTSET, its chain of ancestor loggers is traversed until either an ancestor with a level other than NOTSET is found, or the root is reached.

Also tested in my worker project to verify that _is_ actually the case / it works as intended with my change. It does.

**Comment by JonatanMartens** [comment]
> > If I wanted to disable the logger of the entire `pyzeebe` library could I accomplish this with
> 
> Yes, that (your example) works.
> 
> According to the [logging docs](https://docs.python.org/3/library/logging.html#logger-objects):
> 
> > For example, given a logger with a name of `foo`, loggers with names of `foo.bar`, `foo.bar.baz`, and `foo.bam` are all descendants of `foo`.
> > ...
> > **setLevel(level)**
> > The term ‘delegation to the parent’ means that if a logger has a level of NOTSET, its chain of ancestor loggers is traversed until either an ancestor with a level other than NOTSET is found, or the root is reached.
> 
> Also tested in my worker project to verify that _is_ actually the case / it works as intended with my change. It does.

Great!

**Review by JonatanMartens — APPROVED** [review]

**Pull request merged**
